pipelines:
  image: node:latest

  default:
  - step:
      name: lint
      script:
          - npm run lint
  branches:
    main: 
      - step:
          name: Build
          image: node:latest
          script:
            - npm install
            - npm run build
